import { Image, Search, FileText, Code, Calculator, Ruler, Shield, Share2, Briefcase } from "lucide-react"
import type { Tool } from "./types"

// Sample data for 90 tools (10 per category)
export const toolsData: Tool[] = [
  // Image Tools
  {
    id: "img-1",
    name: "Image to PNG",
    slug: "image-to-png",
    description: "Convert any image to PNG format",
    category: "image",
    icon: Image,
    popular: true,
  },
  {
    id: "img-2",
    name: "Image to JPG",
    slug: "image-to-jpg",
    description: "Convert any image to JPG format",
    category: "image",
    icon: Image,
  },
  {
    id: "img-3",
    name: "Image Resizer",
    slug: "image-resizer",
    description: "Resize your images to any dimension",
    category: "image",
    icon: Image,
    popular: true,
  },
  {
    id: "img-4",
    name: "Image Compressor",
    slug: "image-compressor",
    description: "Compress images without losing quality",
    category: "image",
    icon: Image,
  },
  {
    id: "img-5",
    name: "Image Cropper",
    slug: "image-cropper",
    description: "Crop your images to any size",
    category: "image",
    icon: Image,
  },
  {
    id: "img-6",
    name: "Image to Base64",
    slug: "image-to-base64",
    description: "Convert images to Base64 encoding",
    category: "image",
    icon: Image,
  },
  {
    id: "img-7",
    name: "WebP to PNG",
    slug: "webp-to-png",
    description: "Convert WebP images to PNG format",
    category: "image",
    icon: Image,
  },
  {
    id: "img-8",
    name: "GIF Maker",
    slug: "gif-maker",
    description: "Create animated GIFs from images",
    category: "image",
    icon: Image,
  },
  {
    id: "img-9",
    name: "QR Code Generator",
    slug: "qr-code-generator",
    description: "Generate QR codes for any URL or text",
    category: "image",
    icon: Image,
    popular: true,
  },
  {
    id: "img-10",
    name: "Screenshot to PDF",
    slug: "screenshot-to-pdf",
    description: "Convert screenshots to PDF documents",
    category: "image",
    icon: Image,
  },

  // SEO Tools
  {
    id: "seo-1",
    name: "Meta Tag Generator",
    slug: "meta-tag-generator",
    description: "Generate meta tags for your website",
    category: "seo",
    icon: Search,
  },
  {
    id: "seo-2",
    name: "Keyword Density",
    slug: "keyword-density",
    description: "Check keyword density in your content",
    category: "seo",
    icon: Search,
  },
  {
    id: "seo-3",
    name: "Sitemap Generator",
    slug: "sitemap-generator",
    description: "Generate XML sitemaps for your website",
    category: "seo",
    icon: Search,
    popular: true,
  },
  {
    id: "seo-4",
    name: "Robots.txt Generator",
    slug: "robots-txt-generator",
    description: "Create robots.txt files for your website",
    category: "seo",
    icon: Search,
  },
  {
    id: "seo-5",
    name: "Google Index Checker",
    slug: "google-index-checker",
    description: "Check if your pages are indexed by Google",
    category: "seo",
    icon: Search,
  },
  {
    id: "seo-6",
    name: "Domain Authority",
    slug: "domain-authority",
    description: "Check domain authority of any website",
    category: "seo",
    icon: Search,
  },
  {
    id: "seo-7",
    name: "Backlink Checker",
    slug: "backlink-checker",
    description: "Check backlinks to any website",
    category: "seo",
    icon: Search,
  },
  {
    id: "seo-8",
    name: "Page Speed Checker",
    slug: "page-speed-checker",
    description: "Check page loading speed",
    category: "seo",
    icon: Search,
    popular: true,
  },
  {
    id: "seo-9",
    name: "XML Sitemap Validator",
    slug: "xml-sitemap-validator",
    description: "Validate your XML sitemaps",
    category: "seo",
    icon: Search,
  },
  {
    id: "seo-10",
    name: "Mobile-Friendly Test",
    slug: "mobile-friendly-test",
    description: "Test if your website is mobile-friendly",
    category: "seo",
    icon: Search,
  },

  // Text Tools
  {
    id: "text-1",
    name: "Word Counter",
    slug: "word-counter",
    description: "Count words in your text",
    category: "text",
    icon: FileText,
    popular: true,
  },
  {
    id: "text-2",
    name: "Character Counter",
    slug: "character-counter",
    description: "Count characters in your text",
    category: "text",
    icon: FileText,
  },
  {
    id: "text-3",
    name: "Case Converter",
    slug: "case-converter",
    description: "Convert text case (upper, lower, title)",
    category: "text",
    icon: FileText,
  },
  {
    id: "text-4",
    name: "Plagiarism Checker",
    slug: "plagiarism-checker",
    description: "Check for plagiarism in your text",
    category: "text",
    icon: FileText,
  },
  {
    id: "text-5",
    name: "Grammar Checker",
    slug: "grammar-checker",
    description: "Check grammar in your text",
    category: "text",
    icon: FileText,
    popular: true,
  },
  {
    id: "text-6",
    name: "Text to Speech",
    slug: "text-to-speech",
    description: "Convert text to speech",
    category: "text",
    icon: FileText,
  },
  {
    id: "text-7",
    name: "Speech to Text",
    slug: "speech-to-text",
    description: "Convert speech to text",
    category: "text",
    icon: FileText,
  },
  {
    id: "text-8",
    name: "URL Encoder/Decoder",
    slug: "url-encoder-decoder",
    description: "Encode or decode URLs",
    category: "text",
    icon: FileText,
  },
  {
    id: "text-9",
    name: "Fancy Text Generator",
    slug: "fancy-text-generator",
    description: "Generate fancy text styles",
    category: "text",
    icon: FileText,
  },
  {
    id: "text-10",
    name: "Random Text Generator",
    slug: "random-text-generator",
    description: "Generate random text",
    category: "text",
    icon: FileText,
  },

  // Developer Tools
  {
    id: "dev-1",
    name: "JSON Formatter",
    slug: "json-formatter",
    description: "Format and validate JSON",
    category: "developer",
    icon: Code,
    popular: true,
  },
  {
    id: "dev-2",
    name: "HTML to Markdown",
    slug: "html-to-markdown",
    description: "Convert HTML to Markdown",
    category: "developer",
    icon: Code,
  },
  {
    id: "dev-3",
    name: "CSS Minifier",
    slug: "css-minifier",
    description: "Minify CSS code",
    category: "developer",
    icon: Code,
  },
  {
    id: "dev-4",
    name: "JavaScript Minifier",
    slug: "javascript-minifier",
    description: "Minify JavaScript code",
    category: "developer",
    icon: Code,
  },
  {
    id: "dev-5",
    name: "SQL Formatter",
    slug: "sql-formatter",
    description: "Format SQL queries",
    category: "developer",
    icon: Code,
  },
  {
    id: "dev-6",
    name: "HTACCESS Generator",
    slug: "htaccess-generator",
    description: "Generate .htaccess files",
    category: "developer",
    icon: Code,
  },
  {
    id: "dev-7",
    name: "Markdown to HTML",
    slug: "markdown-to-html",
    description: "Convert Markdown to HTML",
    category: "developer",
    icon: Code,
  },
  {
    id: "dev-8",
    name: "Color Picker",
    slug: "color-picker",
    description: "Pick and convert color codes",
    category: "developer",
    icon: Code,
    popular: true,
  },
  {
    id: "dev-9",
    name: "Base64 Encoder/Decoder",
    slug: "base64-encoder-decoder",
    description: "Encode or decode Base64",
    category: "developer",
    icon: Code,
  },
  {
    id: "dev-10",
    name: "IP Address Lookup",
    slug: "ip-address-lookup",
    description: "Look up information about an IP address",
    category: "developer",
    icon: Code,
  },

  // Math & Calculators
  {
    id: "math-1",
    name: "Percentage Calculator",
    slug: "percentage-calculator",
    description: "Calculate percentages",
    category: "math",
    icon: Calculator,
  },
  {
    id: "math-2",
    name: "Age Calculator",
    slug: "age-calculator",
    description: "Calculate age from birthdate",
    category: "math",
    icon: Calculator,
  },
  {
    id: "math-3",
    name: "BMI Calculator",
    slug: "bmi-calculator",
    description: "Calculate Body Mass Index",
    category: "math",
    icon: Calculator,
    popular: true,
  },
  {
    id: "math-4",
    name: "Loan EMI Calculator",
    slug: "loan-emi-calculator",
    description: "Calculate loan EMI payments",
    category: "math",
    icon: Calculator,
  },
  {
    id: "math-5",
    name: "Scientific Calculator",
    slug: "scientific-calculator",
    description: "Perform scientific calculations",
    category: "math",
    icon: Calculator,
  },
  {
    id: "math-6",
    name: "Discount Calculator",
    slug: "discount-calculator",
    description: "Calculate discounts on prices",
    category: "math",
    icon: Calculator,
    popular: true,
  },
  {
    id: "math-7",
    name: "Currency Converter",
    slug: "currency-converter",
    description: "Convert between currencies",
    category: "math",
    icon: Calculator,
  },
  {
    id: "math-8",
    name: "Time Zone Converter",
    slug: "time-zone-converter",
    description: "Convert between time zones",
    category: "math",
    icon: Calculator,
  },
  {
    id: "math-9",
    name: "Binary to Decimal",
    slug: "binary-to-decimal",
    description: "Convert binary to decimal and vice versa",
    category: "math",
    icon: Calculator,
  },
  {
    id: "math-10",
    name: "Tip Calculator",
    slug: "tip-calculator",
    description: "Calculate tips for restaurants",
    category: "math",
    icon: Calculator,
  },

  // Unit Converters
  {
    id: "unit-1",
    name: "Length Converter",
    slug: "length-converter",
    description: "Convert between length units",
    category: "unit",
    icon: Ruler,
  },
  {
    id: "unit-2",
    name: "Weight Converter",
    slug: "weight-converter",
    description: "Convert between weight units",
    category: "unit",
    icon: Ruler,
  },
  {
    id: "unit-3",
    name: "Speed Converter",
    slug: "speed-converter",
    description: "Convert between speed units",
    category: "unit",
    icon: Ruler,
  },
  {
    id: "unit-4",
    name: "Temperature Converter",
    slug: "temperature-converter",
    description: "Convert between temperature units",
    category: "unit",
    icon: Ruler,
    popular: true,
  },
  {
    id: "unit-5",
    name: "Volume Converter",
    slug: "volume-converter",
    description: "Convert between volume units",
    category: "unit",
    icon: Ruler,
  },
  {
    id: "unit-6",
    name: "Data Storage Converter",
    slug: "data-storage-converter",
    description: "Convert between data storage units",
    category: "unit",
    icon: Ruler,
  },
  {
    id: "unit-7",
    name: "Energy Converter",
    slug: "energy-converter",
    description: "Convert between energy units",
    category: "unit",
    icon: Ruler,
  },
  {
    id: "unit-8",
    name: "Pressure Converter",
    slug: "pressure-converter",
    description: "Convert between pressure units",
    category: "unit",
    icon: Ruler,
  },
  {
    id: "unit-9",
    name: "Fuel Efficiency Converter",
    slug: "fuel-efficiency-converter",
    description: "Convert between fuel efficiency units",
    category: "unit",
    icon: Ruler,
  },
  {
    id: "unit-10",
    name: "Angle Converter",
    slug: "angle-converter",
    description: "Convert between angle units",
    category: "unit",
    icon: Ruler,
  },

  // Security & Encryption Tools
  {
    id: "sec-1",
    name: "MD5 Hash Generator",
    slug: "md5-hash-generator",
    description: "Generate MD5 hashes",
    category: "security",
    icon: Shield,
  },
  {
    id: "sec-2",
    name: "SHA256 Hash Generator",
    slug: "sha256-hash-generator",
    description: "Generate SHA256 hashes",
    category: "security",
    icon: Shield,
  },
  {
    id: "sec-3",
    name: "Password Generator",
    slug: "password-generator",
    description: "Generate secure passwords",
    category: "security",
    icon: Shield,
    popular: true,
  },
  {
    id: "sec-4",
    name: "Random String Generator",
    slug: "random-string-generator",
    description: "Generate random strings",
    category: "security",
    icon: Shield,
  },
  {
    id: "sec-5",
    name: "URL Shortener",
    slug: "url-shortener",
    description: "Shorten long URLs",
    category: "security",
    icon: Shield,
  },
  {
    id: "sec-6",
    name: "IP Geolocation",
    slug: "ip-geolocation",
    description: "Find location from IP address",
    category: "security",
    icon: Shield,
  },
  {
    id: "sec-7",
    name: "SSL Certificate Checker",
    slug: "ssl-certificate-checker",
    description: "Check SSL certificates",
    category: "security",
    icon: Shield,
  },
  {
    id: "sec-8",
    name: "Whois Lookup",
    slug: "whois-lookup",
    description: "Look up domain registration info",
    category: "security",
    icon: Shield,
  },
  {
    id: "sec-9",
    name: "HTTP Headers Checker",
    slug: "http-headers-checker",
    description: "Check HTTP headers of a website",
    category: "security",
    icon: Shield,
  },
  {
    id: "sec-10",
    name: "Privacy Policy Generator",
    slug: "privacy-policy-generator",
    description: "Generate privacy policies",
    category: "security",
    icon: Shield,
  },

  // Social Media Tools
  {
    id: "social-1",
    name: "YouTube Thumbnail Downloader",
    slug: "youtube-thumbnail-downloader",
    description: "Download YouTube thumbnails",
    category: "social",
    icon: Share2,
  },
  {
    id: "social-2",
    name: "Instagram Photo Downloader",
    slug: "instagram-photo-downloader",
    description: "Download Instagram photos",
    category: "social",
    icon: Share2,
  },
  {
    id: "social-3",
    name: "Twitter Video Downloader",
    slug: "twitter-video-downloader",
    description: "Download Twitter videos",
    category: "social",
    icon: Share2,
  },
  {
    id: "social-4",
    name: "Facebook Video Downloader",
    slug: "facebook-video-downloader",
    description: "Download Facebook videos",
    category: "social",
    icon: Share2,
    popular: true,
  },
  {
    id: "social-5",
    name: "TikTok Video Downloader",
    slug: "tiktok-video-downloader",
    description: "Download TikTok videos",
    category: "social",
    icon: Share2,
  },
  {
    id: "social-6",
    name: "YouTube Tags Extractor",
    slug: "youtube-tags-extractor",
    description: "Extract tags from YouTube videos",
    category: "social",
    icon: Share2,
  },
  {
    id: "social-7",
    name: "Hashtag Generator",
    slug: "hashtag-generator",
    description: "Generate hashtags for social media",
    category: "social",
    icon: Share2,
  },
  {
    id: "social-8",
    name: "Social Media Post Generator",
    slug: "social-media-post-generator",
    description: "Generate social media posts",
    category: "social",
    icon: Share2,
  },
  {
    id: "social-9",
    name: "Emoji Keyboard",
    slug: "emoji-keyboard",
    description: "Copy and paste emojis",
    category: "social",
    icon: Share2,
  },
  {
    id: "social-10",
    name: "Twitter Character Counter",
    slug: "twitter-character-counter",
    description: "Count characters for Twitter",
    category: "social",
    icon: Share2,
  },

  // Miscellaneous Tools
  {
    id: "misc-1",
    name: "Barcode Generator",
    slug: "barcode-generator",
    description: "Generate barcodes",
    category: "misc",
    icon: Briefcase,
  },
  {
    id: "misc-2",
    name: "Meme Generator",
    slug: "meme-generator",
    description: "Create memes with custom text",
    category: "misc",
    icon: Briefcase,
    popular: true,
  },
  {
    id: "misc-3",
    name: "Resume Builder",
    slug: "resume-builder",
    description: "Build professional resumes",
    category: "misc",
    icon: Briefcase,
  },
  {
    id: "misc-4",
    name: "Invoice Generator",
    slug: "invoice-generator",
    description: "Generate professional invoices",
    category: "misc",
    icon: Briefcase,
  },
  {
    id: "misc-5",
    name: "Business Name Generator",
    slug: "business-name-generator",
    description: "Generate business name ideas",
    category: "misc",
    icon: Briefcase,
  },
  {
    id: "misc-6",
    name: "Lottery Number Generator",
    slug: "lottery-number-generator",
    description: "Generate random lottery numbers",
    category: "misc",
    icon: Briefcase,
  },
  {
    id: "misc-7",
    name: "Coin Flip Simulator",
    slug: "coin-flip-simulator",
    description: "Simulate flipping a coin",
    category: "misc",
    icon: Briefcase,
  },
  {
    id: "misc-8",
    name: "Random Number Generator",
    slug: "random-number-generator",
    description: "Generate random numbers",
    category: "misc",
    icon: Briefcase,
  },
  {
    id: "misc-9",
    name: "Dice Roller",
    slug: "dice-roller",
    description: "Simulate rolling dice",
    category: "misc",
    icon: Briefcase,
  },
  {
    id: "misc-10",
    name: "Internet Speed Test",
    slug: "internet-speed-test",
    description: "Test your internet connection speed",
    category: "misc",
    icon: Briefcase,
    popular: true,
  },
]

