import {
  Image,
  Search,
  FileText,
  Code,
  Calculator,
  Ruler,
  Shield,
  Share2,
  Sparkles,
  Palette,
  Crop,
  ImagePlus,
  FileImage,
  Contrast,
  Scissors,
  Globe,
  BarChart,
  LinkIcon,
  FileSearch,
  Hash,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Type,
  Pilcrow,
  Braces,
  Terminal,
  Database,
  Server,
  GitBranch,
  Percent,
  Plus,
  Minus,
  Divide,
  Sigma,
  Clock,
  Scale,
  Thermometer,
  RulerIcon,
  Lock,
  Key,
  FileKey,
  QrCode,
  Facebook,
  Twitter,
  Instagram,
  Youtube,
  Wand2,
  Zap,
  Calendar,
  FileCheck,
  Shuffle,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

// Category type
interface Category {
  id: string
  name: string
  description: string
  icon: LucideIcon
  color: string
  iconColor: string
  toolCount: number
}

// Tool type
interface Tool {
  id: string
  name: string
  description: string
  categoryId: string
  category: string
  icon: LucideIcon
  color: string
  iconColor: string
  featured?: boolean
  popular?: boolean
  new?: boolean
}

// Categories data
export const categories: Category[] = [
  {
    id: "image-tools",
    name: "Image Tools",
    description: "Edit, convert, and optimize your images with these powerful tools",
    icon: Image,
    color: "bg-pink-500",
    iconColor: "text-pink-500",
    toolCount: 10,
  },
  {
    id: "seo-tools",
    name: "SEO Tools",
    description: "Improve your website's search engine rankings with these SEO tools",
    icon: Search,
    color: "bg-blue-500",
    iconColor: "text-blue-500",
    toolCount: 10,
  },
  {
    id: "text-tools",
    name: "Text Tools",
    description: "Manipulate, format, and analyze text with these handy utilities",
    icon: FileText,
    color: "bg-purple-500",
    iconColor: "text-purple-500",
    toolCount: 10,
  },
  {
    id: "developer-tools",
    name: "Developer Tools",
    description: "Essential tools for web developers and programmers",
    icon: Code,
    color: "bg-green-500",
    iconColor: "text-green-500",
    toolCount: 10,
  },
  {
    id: "math-calculators",
    name: "Math & Calculators",
    description: "Solve mathematical problems and perform calculations",
    icon: Calculator,
    color: "bg-yellow-500",
    iconColor: "text-yellow-500",
    toolCount: 10,
  },
  {
    id: "unit-converters",
    name: "Unit Converters",
    description: "Convert between different units of measurement",
    icon: Ruler,
    color: "bg-indigo-500",
    iconColor: "text-indigo-500",
    toolCount: 10,
  },
  {
    id: "security-tools",
    name: "Security & Encryption",
    description: "Protect your data with encryption and security tools",
    icon: Shield,
    color: "bg-red-500",
    iconColor: "text-red-500",
    toolCount: 10,
  },
  {
    id: "social-media",
    name: "Social Media Tools",
    description: "Enhance your social media presence with these tools",
    icon: Share2,
    color: "bg-cyan-500",
    iconColor: "text-cyan-500",
    toolCount: 10,
  },
  {
    id: "misc-tools",
    name: "Miscellaneous Tools",
    description: "A collection of useful tools that don't fit in other categories",
    icon: Sparkles,
    color: "bg-orange-500",
    iconColor: "text-orange-500",
    toolCount: 10,
  },
]

// Tools data
export const tools: Tool[] = [
  // Image Tools
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize your images to any dimension while maintaining quality",
    categoryId: "image-tools",
    category: "Image Tools",
    icon: Crop,
    color: "bg-pink-500",
    iconColor: "text-pink-500",
    featured: true,
    popular: true,
  },
  {
    id: "image-converter",
    name: "Image Converter",
    description: "Convert images between different formats (JPG, PNG, WebP, etc.)",
    categoryId: "image-tools",
    category: "Image Tools",
    icon: ImagePlus,
    color: "bg-pink-500",
    iconColor: "text-pink-500",
    popular: true,
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Compress images to reduce file size without losing quality",
    categoryId: "image-tools",
    category: "Image Tools",
    icon: FileImage,
    color: "bg-pink-500",
    iconColor: "text-pink-500",
    featured: true,
  },
  {
    id: "image-editor",
    name: "Image Editor",
    description: "Edit your images with filters, effects, and adjustments",
    categoryId: "image-tools",
    category: "Image Tools",
    icon: Palette,
    color: "bg-pink-500",
    iconColor: "text-pink-500",
  },
  {
    id: "image-enhancer",
    name: "Image Enhancer",
    description: "Enhance image quality and fix common issues",
    categoryId: "image-tools",
    category: "Image Tools",
    icon: Contrast,
    color: "bg-pink-500",
    iconColor: "text-pink-500",
  },
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove backgrounds from images with AI technology",
    categoryId: "image-tools",
    category: "Image Tools",
    icon: Scissors,
    color: "bg-pink-500",
    iconColor: "text-pink-500",
    new: true,
    popular: true,
  },

  // SEO Tools
  {
    id: "keyword-research",
    name: "Keyword Research",
    description: "Find the best keywords to target for your content",
    categoryId: "seo-tools",
    category: "SEO Tools",
    icon: Search,
    color: "bg-blue-500",
    iconColor: "text-blue-500",
    featured: true,
    popular: true,
  },
  {
    id: "seo-analyzer",
    name: "SEO Analyzer",
    description: "Analyze your website for SEO issues and get recommendations",
    categoryId: "seo-tools",
    category: "SEO Tools",
    icon: Globe,
    color: "bg-blue-500",
    iconColor: "text-blue-500",
    popular: true,
  },
  {
    id: "rank-tracker",
    name: "Rank Tracker",
    description: "Track your website's search engine rankings over time",
    categoryId: "seo-tools",
    category: "SEO Tools",
    icon: BarChart,
    color: "bg-blue-500",
    iconColor: "text-blue-500",
  },
  {
    id: "backlink-checker",
    name: "Backlink Checker",
    description: "Check and analyze backlinks pointing to your website",
    categoryId: "seo-tools",
    category: "SEO Tools",
    icon: LinkIcon,
    color: "bg-blue-500",
    iconColor: "text-blue-500",
  },
  {
    id: "meta-tag-generator",
    name: "Meta Tag Generator",
    description: "Generate optimized meta tags for your web pages",
    categoryId: "seo-tools",
    category: "SEO Tools",
    icon: FileSearch,
    color: "bg-blue-500",
    iconColor: "text-blue-500",
    featured: true,
  },
  {
    id: "keyword-density",
    name: "Keyword Density Checker",
    description: "Check the keyword density of your content",
    categoryId: "seo-tools",
    category: "SEO Tools",
    icon: Hash,
    color: "bg-blue-500",
    iconColor: "text-blue-500",
    new: true,
  },

  // Text Tools
  {
    id: "text-formatter",
    name: "Text Formatter",
    description: "Format and beautify your text with various options",
    categoryId: "text-tools",
    category: "Text Tools",
    icon: AlignCenter,
    color: "bg-purple-500",
    iconColor: "text-purple-500",
    featured: true,
    popular: true,
  },
  {
    id: "text-case-converter",
    name: "Text Case Converter",
    description: "Convert text between different cases (uppercase, lowercase, title case)",
    categoryId: "text-tools",
    category: "Text Tools",
    icon: Type,
    color: "bg-purple-500",
    iconColor: "text-purple-500",
    popular: true,
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text for your designs",
    categoryId: "text-tools",
    category: "Text Tools",
    icon: Pilcrow,
    color: "bg-purple-500",
    iconColor: "text-purple-500",
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, and paragraphs in your text",
    categoryId: "text-tools",
    category: "Text Tools",
    icon: AlignLeft,
    color: "bg-purple-500",
    iconColor: "text-purple-500",
    featured: true,
  },
  {
    id: "text-diff",
    name: "Text Diff Checker",
    description: "Compare two texts and highlight the differences",
    categoryId: "text-tools",
    category: "Text Tools",
    icon: AlignRight,
    color: "bg-purple-500",
    iconColor: "text-purple-500",
    new: true,
  },

  // Developer Tools
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format and validate your JSON data",
    categoryId: "developer-tools",
    category: "Developer Tools",
    icon: Braces,
    color: "bg-green-500",
    iconColor: "text-green-500",
    featured: true,
    popular: true,
  },
  {
    id: "code-beautifier",
    name: "Code Beautifier",
    description: "Beautify and format your code (HTML, CSS, JS, etc.)",
    categoryId: "developer-tools",
    category: "Developer Tools",
    icon: Code,
    color: "bg-green-500",
    iconColor: "text-green-500",
    popular: true,
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify your SQL queries",
    categoryId: "developer-tools",
    category: "Developer Tools",
    icon: Database,
    color: "bg-green-500",
    iconColor: "text-green-500",
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test and debug your regular expressions",
    categoryId: "developer-tools",
    category: "Developer Tools",
    icon: Terminal,
    color: "bg-green-500",
    iconColor: "text-green-500",
    featured: true,
  },
  {
    id: "cron-expression",
    name: "Cron Expression Generator",
    description: "Generate and validate cron expressions",
    categoryId: "developer-tools",
    category: "Developer Tools",
    icon: Server,
    color: "bg-green-500",
    iconColor: "text-green-500",
  },
  {
    id: "git-cheatsheet",
    name: "Git Cheatsheet",
    description: "Quick reference for common Git commands",
    categoryId: "developer-tools",
    category: "Developer Tools",
    icon: GitBranch,
    color: "bg-green-500",
    iconColor: "text-green-500",
    new: true,
  },

  // Math & Calculators
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages, increases, and decreases",
    categoryId: "math-calculators",
    category: "Math & Calculators",
    icon: Percent,
    color: "bg-yellow-500",
    iconColor: "text-yellow-500",
    featured: true,
    popular: true,
  },
  {
    id: "scientific-calculator",
    name: "Scientific Calculator",
    description: "Perform complex mathematical calculations",
    categoryId: "math-calculators",
    category: "Math & Calculators",
    icon: Calculator,
    color: "bg-yellow-500",
    iconColor: "text-yellow-500",
    popular: true,
  },
  {
    id: "equation-solver",
    name: "Equation Solver",
    description: "Solve mathematical equations step by step",
    categoryId: "math-calculators",
    category: "Math & Calculators",
    icon: Sigma,
    color: "bg-yellow-500",
    iconColor: "text-yellow-500",
  },
  {
    id: "fraction-calculator",
    name: "Fraction Calculator",
    description: "Perform calculations with fractions",
    categoryId: "math-calculators",
    category: "Math & Calculators",
    icon: Divide,
    color: "bg-yellow-500",
    iconColor: "text-yellow-500",
  },
  {
    id: "basic-calculator",
    name: "Basic Calculator",
    description: "Perform basic arithmetic operations",
    categoryId: "math-calculators",
    category: "Math & Calculators",
    icon: Plus,
    color: "bg-yellow-500",
    iconColor: "text-yellow-500",
    featured: true,
  },

  // Unit Converters
  {
    id: "length-converter",
    name: "Length Converter",
    description: "Convert between different units of length",
    categoryId: "unit-converters",
    category: "Unit Converters",
    icon: RulerIcon,
    color: "bg-indigo-500",
    iconColor: "text-indigo-500",
    featured: true,
    popular: true,
  },
  {
    id: "weight-converter",
    name: "Weight Converter",
    description: "Convert between different units of weight",
    categoryId: "unit-converters",
    category: "Unit Converters",
    icon: Scale,
    color: "bg-indigo-500",
    iconColor: "text-indigo-500",
  },
  {
    id: "temperature-converter",
    name: "Temperature Converter",
    description: "Convert between Celsius, Fahrenheit, and Kelvin",
    categoryId: "unit-converters",
    category: "Unit Converters",
    icon: Thermometer,
    color: "bg-indigo-500",
    iconColor: "text-indigo-500",
    popular: true,
  },
  {
    id: "time-converter",
    name: "Time Converter",
    description: "Convert between different units of time",
    categoryId: "unit-converters",
    category: "Unit Converters",
    icon: Clock,
    color: "bg-indigo-500",
    iconColor: "text-indigo-500",
  },
  {
    id: "currency-converter",
    name: "Currency Converter",
    description: "Convert between different currencies with live rates",
    categoryId: "unit-converters",
    category: "Unit Converters",
    icon: Minus,
    color: "bg-indigo-500",
    iconColor: "text-indigo-500",
    featured: true,
    new: true,
  },

  // Security & Encryption
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate strong and secure passwords",
    categoryId: "security-tools",
    category: "Security & Encryption",
    icon: Lock,
    color: "bg-red-500",
    iconColor: "text-red-500",
    featured: true,
    popular: true,
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate hash values for your text or files",
    categoryId: "security-tools",
    category: "Security & Encryption",
    icon: Key,
    color: "bg-red-500",
    iconColor: "text-red-500",
  },
  {
    id: "encryption-tool",
    name: "Encryption Tool",
    description: "Encrypt and decrypt your text with various algorithms",
    categoryId: "security-tools",
    category: "Security & Encryption",
    icon: FileKey,
    color: "bg-red-500",
    iconColor: "text-red-500",
    popular: true,
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes for text, URLs, and more",
    categoryId: "security-tools",
    category: "Security & Encryption",
    icon: QrCode,
    color: "bg-red-500",
    iconColor: "text-red-500",
    featured: true,
  },

  // Social Media Tools
  {
    id: "facebook-tools",
    name: "Facebook Tools",
    description: "Tools to enhance your Facebook marketing",
    categoryId: "social-media",
    category: "Social Media Tools",
    icon: Facebook,
    color: "bg-cyan-500",
    iconColor: "text-cyan-500",
    featured: true,
  },
  {
    id: "twitter-tools",
    name: "Twitter Tools",
    description: "Tools to improve your Twitter presence",
    categoryId: "social-media",
    category: "Social Media Tools",
    icon: Twitter,
    color: "bg-cyan-500",
    iconColor: "text-cyan-500",
    popular: true,
  },
  {
    id: "instagram-tools",
    name: "Instagram Tools",
    description: "Tools to boost your Instagram engagement",
    categoryId: "social-media",
    category: "Social Media Tools",
    icon: Instagram,
    color: "bg-cyan-500",
    iconColor: "text-cyan-500",
    featured: true,
    popular: true,
  },
  {
    id: "youtube-tools",
    name: "YouTube Tools",
    description: "Tools to optimize your YouTube channel",
    categoryId: "social-media",
    category: "Social Media Tools",
    icon: Youtube,
    color: "bg-cyan-500",
    iconColor: "text-cyan-500",
  },

  // Miscellaneous Tools
  {
    id: "random-generator",
    name: "Random Generator",
    description: "Generate random numbers, names, passwords, and more",
    categoryId: "misc-tools",
    category: "Miscellaneous Tools",
    icon: Shuffle,
    color: "bg-orange-500",
    iconColor: "text-orange-500",
    featured: true,
  },
  {
    id: "file-converter",
    name: "File Converter",
    description: "Convert files between different formats",
    categoryId: "misc-tools",
    category: "Miscellaneous Tools",
    icon: FileCheck,
    color: "bg-orange-500",
    iconColor: "text-orange-500",
    popular: true,
  },
  {
    id: "date-calculator",
    name: "Date Calculator",
    description: "Calculate the difference between dates",
    categoryId: "misc-tools",
    category: "Miscellaneous Tools",
    icon: Calendar,
    color: "bg-orange-500",
    iconColor: "text-orange-500",
  },
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Pick and convert colors in different formats",
    categoryId: "misc-tools",
    category: "Miscellaneous Tools",
    icon: Wand2,
    color: "bg-orange-500",
    iconColor: "text-orange-500",
    featured: true,
    popular: true,
  },
  {
    id: "url-shortener",
    name: "URL Shortener",
    description: "Shorten long URLs for easier sharing",
    categoryId: "misc-tools",
    category: "Miscellaneous Tools",
    icon: Zap,
    color: "bg-orange-500",
    iconColor: "text-orange-500",
    new: true,
  },
]

